version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: dermassist-api:latest
    container_name: dermassist-backend
    ports:
      - "8000:8000"
    volumes:
      # Mount the heatmaps directory to persist generated images locally
      - ./heatmaps:/app/heatmaps
    environment:
      # For the rate limiter to find Redis
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: "redis:alpine"
    container_name: dermassist-redis
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  redis-data:
    driver: local
