services:
  # The FastAPI backend service
  - type: web
    name: dermassist-backend
    env: docker
    # Replace with your Docker Hub username/organization
    image:
      path: aaronchen2002/dermassist-api:latest
    plan: free # Use the free instance type
    ports:
      - 8000:8000
    healthCheckPath: /health
    envVars:
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: dermassist-redis
          property: connectionString
      - key: API_KEYS
        # This will be set in the Render dashboard, not here
        value: ""

  # The Redis instance for rate limiting
  - type: keyvalue
    name: dermassist-redis
    plan: free # Use the free instance type
    ipAllowList: [] # Allow only internal connections 