services:
  # The FastAPI backend service
  - type: web
    name: dermassist-backend
    env: docker
    # Replace with your Docker Hub username/organization
    image:
      path: aaronchen2002/dermassist-api:latest
    plan: free # Use the free instance type
    ports:
      - 8000:8000
    healthCheckPath: /health
    envVars:
      - key: REDIS_URL
        fromService:
          type: private
          name: dermassist-redis
          property: url
      - key: API_KEYS
        # This will be set in the Render dashboard, not here
        value: ""

  # The Redis instance for rate limiting
  - type: private
    name: dermassist-redis
    env: docker
    image:
      path: redis:alpine
    plan: free # Use the free instance type
    ports:
      - 6379:6379 