services:
  # The FastAPI backend service
  - type: web
    name: dermassist-backend
    runtime: docker
    repo: https://github.com/AaronChen2002/dermassist
    branch: main
    autoDeploy: true
    # A pre-deploy command to download the model file
    preDeployCommand: |
      mkdir -p models
      curl -L 'https://docs.google.com/uc?export=download&id=1q-4aY_8...YOUR_FILE_ID...&confirm=t' -o models/dermassist_mobilenet_v2.pt
    plan: free # Use the free instance type
    healthCheckPath: /health
    envVars:
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: dermassist-redis
          property: connectionString
      - key: API_KEYS
        # This will be set in the Render dashboard, not here
        value: ""

  # The Redis instance for rate limiting
  - type: keyvalue
    name: dermassist-redis
    plan: free # Use the free instance type
    ipAllowList: [] # Allow only internal connections 