services:
  # The FastAPI backend service
  - type: web
    name: dermassist-backend
    runtime: docker
    repo: https://github.com/AaronChen2002/dermassist
    branch: main
    autoDeploy: true
    plan: free # Use the free instance type
    healthCheckPath: /health
    envVars:
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: dermassist-redis
          property: connectionString
      - key: API_KEYS
        # This will be set in the Render dashboard, not here
        value: ""

  # The Redis instance for rate limiting
  - type: keyvalue
    name: dermassist-redis
    plan: free # Use the free instance type
    ipAllowList: [] # Allow only internal connections 