name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install lint dependencies
        run: |
          pip install ruff

      - name: Run linter
        run: |
          ruff check .

  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create models directory
        run: mkdir -p models

      - name: Download model from GDrive
        run: curl -L -o models/dermassist_mobilenet_v2.pt 'https://drive.google.com/uc?export=download&id=1XTy-JO4U7Lf8UKb4YwVlNNe7ytTUJYwd'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest
